### ISSUE TITLE
Version 3.0.0 alpha 30 crashes on startup

### ISSUE THREAD

**Issue by GiacomoST** [t0bst4r/home-assistant-matter-hub#137] opened 2024-11-14 15:45 UTC
[logs.txt](https://github.com/user-attachments/files/17751061/logs.txt)

**Comment by dkuytrewq** [comment] 2024-11-14 18:10
[491eb00d_hamh_2024-11-14T18-07-23.025Z.log](https://github.com/user-attachments/files/17754573/491eb00d_hamh_2024-11-14T18-07-23.025Z.log)

Same here

**Comment by t0bst4r** [comment] 2024-11-14 19:39
Duplicate of #134

**Closed by t0bst4r** 2024-11-14 19:39 UTC
