### ISSUE TITLE
Failed to fetch error after adding new hub

### ISSUE THREAD

**Issue by pana800** [t0bst4r/home-assistant-matter-hub#13] opened 2024-10-28 09:25 UTC
![image](https://github.com/user-attachments/assets/a25a3559-4ea4-45cd-be74-f51a4a56429d)
![image](https://github.com/user-attachments/assets/e3920f2c-bfe0-4c64-accd-3e04942db54e)
The add on stops and screen shows this error.

**Comment by t0bst4r** [comment] 2024-10-28 09:27
Can you add the addon logs?

**Comment by levanLuongnt** [comment] 2024-10-28 09:44
> Can you add the addon logs?

 2024-10-28T09:43:02.521Z ] [ INFO  ] [ matter.js / Node                         ]: 0a64012c45bd40a9b1e57dbabb680faa going online
[ 2024-10-28T09:43:02.555Z ] [ ERROR ] [ matter.js / Logger                       ]: Unhandled error detected: Cannot read properties of undefined (reading 'attributes')
  at new BinarySensorDevice (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1889:49)
  at binary_sensor (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2668:32)
  at createDevice (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2644:10)
  at Bridge.createDevices (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2737:26)
  at Bridge.start (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2729:20)
  at async BridgeService.create (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2826:9)
  at async file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:698:24
file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1889
        const deviceClass = entity.initialState.attributes.device_class;
                                                ^

TypeError: Cannot read properties of undefined (reading 'attributes')
    at new BinarySensorDevice (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1889:49)
    at binary_sensor (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2668:32)
    at createDevice (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2644:10)
    at Bridge.createDevices (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2737:26)
    at Bridge.start (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2729:20)
    at async BridgeService.create (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2826:9)
    at async file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:698:24

Node.js v18.20.4
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by t0bst4r** [comment] 2024-10-28 09:51
Thank you! This is a duplicate of #11

**Closed by t0bst4r** 2024-10-28 09:51 UTC
Labels: bug
