### ISSUE TITLE
Can't control air conditioner from Google home

### ISSUE THREAD

**Issue by datvista** [t0bst4r/home-assistant-matter-hub#91] opened 2024-11-09 01:48 UTC
Can't control air conditioner from Google home even though status is still updated

**Comment by datvista** [comment] 2024-11-09 04:46
[logs-2.txt](https://github.com/user-attachments/files/17685998/logs-2.txt)

**Comment by t0bst4r** [comment] 2024-11-09 11:06
This is a duplicate of #73 
I have already build a fix, but due to some small issue it's not yet released.

**Closed by t0bst4r** 2024-11-09 11:06 UTC

**Comment by datvista** [comment] 2024-11-09 15:24
Thank you
