### ISSUE TITLE
[Bug]: container crashes to launch

### ISSUE THREAD

**Issue by myevit** [t0bst4r/home-assistant-matter-hub#265] opened 2024-12-06 01:12 UTC
### Version

alfa50-51

### Matter Controller

alexa

[491eb00d_hamh_2024-12-06T01-09-54.645Z.log](https://github.com/user-attachments/files/18031443/491eb00d_hamh_2024-12-06T01-09-54.645Z.log)
Here is my big log

alfa49 works just fine

**Comment by myevit** [comment] 2024-12-07 19:17
Alfa52

[ 2024-12-07T19:16:09.947Z ] [ ERROR ] [ Matter / Logger                                    ]: Unhandled error detected: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
Node.js v18.20.4

**Comment by t0bst4r** [comment] 2024-12-09 09:02
this is a duplicate of #264

**Closed by t0bst4r** 2024-12-09 09:02 UTC
Labels: bug
