### ISSUE TITLE
Error after updating to 3.0.0-alpha.8

### ISSUE THREAD

**Issue by nehasjains** [t0bst4r/home-assistant-matter-hub#18] opened 2024-10-28 14:44 UTC
```
TypeError: Cannot read properties of undefined (reading 'attributes')
    at SensorDevice (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2065:43)
    at sensor (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2669:25)
    at createDevice (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2644:10)
    at Bridge.createDevices (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2737:26)
    at async Bridge.start (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2729:9)
    at async BridgeService.start (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2804:11)
    at async handler (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:3307:5)
s6-rc: info: service legacy-services: stopping
```

**Comment by MartinSaldert** [comment] 2024-10-28 14:59
Same here!

**Comment by t0bst4r** [comment] 2024-10-29 06:04
Duplicate of #11

**Closed by t0bst4r** 2024-10-29 06:04 UTC
