### ISSUE TITLE
Problems adding devices with Include/Exclude

### ISSUE THREAD

**Issue by joacim69** [t0bst4r/home-assistant-matter-hub#14] opened 2024-10-28 09:44 UTC
Hi! I've been trying for hours now to add more than lights.
To be able to use Flic buttons I successfully, with the old bridge, use input_boolean switches and use automations for each one, which worked great.
however, when trying to populate them I seem to do something wrong.

I've tried with patterns, labels, domains to find either just input, input_boolean* or the specific entity, but I can just find the lights entitites. What am I doing wrong?

Like this:
```
{
  "name": "My Hub 3",
  "port": 5543,
  "filter": {
    "include": [
      { "type": "domain", "value": "light" },
      { "type": "label", "value": "input*" }
    ],
    "exclude": [
     
 
    ]
  }
}
```

Or this:

```
{
  "name": "My Hub ny",
  "port": 5543,
  "filter": {
    "include": [
      {
        "type": "domain",
        "value": "light"
      },
      {
        "type": "domain",
        "value": "Switch ändra all belysning",
   
    ],
    "exclude": []
  }
}
```

**Comment by t0bst4r** [comment] 2024-10-28 10:02
In your first example you are using the "label" type, but use a pattern as value.
If you have type "label", you have to use an existing label from home assistant.
In your second example you are using type "domain" and the value seems to be the name of an entity.

To solve your problem use one of the following:

```
{ "type": "domain", "value": "input_boolean" }
```

or 

```
{ "type": "pattern", "value": "input_boolean.*" }
```

or

```
{ "type": "pattern", "value": "input_boolean.my_specific_entity" }
```

**Comment by joacim69** [comment] 2024-10-28 10:40
Thanks for your help. I created a very simple one, but it finds nothing anyways. Do I have to restart the addon each time or is there anything else to try?
![Skärmbild 2024-10-28 113938](https://github.com/user-attachments/assets/f6a37e13-ea9b-4730-8207-27dfc777e02b)

{
  "name": "testing",
  "port": 5541,
  "filter": {
    "include": [
      {
        "type": "domain",
        "value": "input_boolean"
      }
    ],
    "exclude": []
  }
}

**Comment by joacim69** [comment] 2024-10-28 10:42
This is the Boolean switch I'd like to populate
![Skärmbild 2024-10-28 114159](https://github.com/user-attachments/assets/c736172a-ff69-4dbd-a7a5-04aea1afda31)

**Comment by nehasjains** [comment] 2024-10-28 10:51
I think input_boolean entities are not getting imported. For me input_boolean entities are not getting imported

**Comment by nehasjains** [comment] 2024-10-28 10:52
> In your first example you are using the "label" type, but use a pattern as value. If you have type "label", you have to use an existing label from home assistant. In your second example you are using type "domain" and the value seems to be the name of an entity.
> 
> To solve your problem use one of the following:
> 
> ```
> { "type": "domain", "value": "input_boolean" }
> ```
> 
> or
> 
> ```
> { "type": "pattern", "value": "input_boolean.*" }
> ```
> 
> or
> 
> ```
> { "type": "pattern", "value": "input_boolean.my_specific_entity" }
> ```

Tried these... but inpur_boolean entities not getting imported

**Comment by joacim69** [comment] 2024-10-28 15:50
I'm just happy that I wasn't totally lost 😎

**Comment by truongbber** [comment] 2024-10-28 21:07
pattern switch, light and climate not working

**Comment by t0bst4r** [comment] 2024-10-29 06:07
I created a new issue for the missing domains: #21 

@truongbber what is your issue about? Do you see any error logs?

**Comment by joacim69** [comment] 2024-10-29 08:45
Yay, now Input_booleans work with alpha 10 :-)

**Comment by pana800** [comment] 2024-10-29 08:50
Is there any way to modify the filter rules for the created bridge? At the moment, I only delete an create new one for adding or removing rules.
Thanks

**Comment by t0bst4r** [comment] 2024-10-29 08:51
At the moment editing is not possible.
I'll create a new issue for that to track.

**Comment by joacim69** [comment] 2024-10-29 10:26
For what it's worth, here's a working config file:

{
"name": "matterhub new",
"port": 5531,
"filter": {
"include": [
{
"type": "domain",
"value": "input_boolean" },
 { "type": "domain", "value": "light" },
{ "type": "domain", "value": "automation" }
],
"exclude": []
}
}

**Comment by t0bst4r** [comment] 2024-10-29 17:08
wow... it could be caused by this 🤣 

![grafik](https://github.com/user-attachments/assets/5be764e2-72f2-419e-a718-c914e2a9a947)

**Comment by t0bst4r** [comment] 2024-10-29 17:22
I'll close this issue, since #30 is more specific.

**Closed by t0bst4r** 2024-10-29 17:23 UTC
Labels: question
